services:
  devcontainer:
    command: sh -exc 'while sleep 1m; do :; done'
    image: public.ecr.aws/acilearning/haskell:${GHC_VERSION:-9.6.2}-ecbdf5ff8c0a4244a73e790303a8d61776cebd8e-arm64
    init: true
    volumes:
      - .:/workspaces/haskell-packages
      - ./volumes/cabal-cache:/home/vscode/.cache/cabal
      - ./volumes/cabal-state:/home/vscode/.local/state/cabal
    working_dir: /workspaces/haskell-packages
