# snapshot: lts-14.27 # GHC 8.6
snapshot: lts-15.4 # GHC 8.8
# compiler: ghc-8.10.1 # GHC 8.10 (use with LTS-15.4)

packages:
  - autoexporter
  - burrito
  - derulo
  - flow
  - github-release
  - json-feed
  - lackey
  - list-singleton
  - rampart
  - ratel
  - ratel-wai
  - rattletrap
  - salve
  - strive
  - wuss

extra-deps:

  # https://github.com/kolmodin/binary-bits/pull/13
  - git: https://github.com/tfausak/binary-bits
    commit: ac97db5fb88940ac4b05481d3d1b36005a715172
