# snapshot: lts-14.27 # GHC 8.6
snapshot: lts-15.13 # GHC 8.8
# compiler: ghc-8.10.1 # GHC 8.10 (use with LTS-15.13)

packages:
  - autoexporter
  - burrito
  - derulo
  - flow
  - github-release
  - json-feed
  - lackey
  - list-singleton
  - rampart
  - ratel
  - ratel-wai
  - rattletrap
  - salve
  - splint
  - strive
  - wuss

extra-deps:

  # https://github.com/kolmodin/binary-bits/pull/13
  - git: https://github.com/tfausak/binary-bits
    commit: ac97db5fb88940ac4b05481d3d1b36005a715172

  - extra-1.7.2
  - ghc-lib-parser-8.10.1.20200523
  - ghc-lib-parser-ex-8.10.0.11
  - hlint-3.1.3
  - lens-4.19.2

allow-newer: true
