resolver: lts-17.0

packages:
  - autoexporter
  - burrito
  - caerbannog
  - derulo
  - flow
  - github-release
  - json-feed
  - lackey
  - list-singleton
  - rampart
  - ratel
  - ratel-wai
  - rattletrap
  - salve
  - splint
  - strive
  - witch
  - wuss
