snapshot: lts
packages:
  - autoexporter
  - burrito
  - cabal-gild
  - flow
  - github-release
  - json-feed
  - lackey
  - patrol
  - rampart
  - ratel
  - ratel-wai
  - salve
  - saturn
  - strive
  - witch
  - wuss
extra-deps:
  - optparse-generic-1.5.2@sha256:d3f68b7c100009cd8e91ce3d0b0b2eabb6a4303954a54e5628bd5c78efcc3a19,2337
allow-newer-deps:
  - optparse-generic
