services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: ghcr.io/acilearning/docker-haskell:9.0.2
    init: true
    volumes:
      - ..:/workspaces/haskell-packages
      - cabal:/home/haskell/.cabal
      - cabal-store:/cabal-store
volumes:
  cabal: null
  cabal-store:
    external: true
