jobs:
  build-cabal:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: haskell/ghcup-setup@v1
        with:
          ghc: ${{ matrix.ghc }}
          cabal: latest
      - run: ghc-pkg list
      - run: cabal configure --enable-tests --flags=pedantic --jobs
      - run: cat cabal.project.local
      - run: cabal update
      - run: cabal freeze
      - run: cat cabal.project.freeze
      - run: cabal outdated --v2-freeze-file
      - uses: actions/cache@v4
        with:
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          path: ~/.local/state/cabal
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build --only-download all
      - run: cabal build --only-dependencies all
      - run: cabal build all
      - run: cabal run -- burrito-test-suite --randomize --strict
    strategy:
      matrix:
        include:
          - ghc: 9.12
            os: macos-13
          - ghc: 9.12
            os: macos-14
          - ghc: 9.8
            os: ubuntu-24.04
          - ghc: '9.10'
            os: ubuntu-24.04
          - ghc: 9.12
            os: ubuntu-24.04
          - ghc: 9.12
            os: windows-2022
  build-stack:
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack-root
    name: Stackage ${{ matrix.snapshot }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: haskell/ghcup-setup@v1
        with:
          stack: latest
      - uses: actions/cache@v4
        with:
          key: ${{ matrix.snapshot }}
          path: |
            .stack-root
            .stack-work
      - run: stack --snapshot ${{ matrix.snapshot }} test --no-run-tests
    strategy:
      matrix:
        snapshot:
          - lts
          - nightly
name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created
